name: Push Docker Image

on:
  push:
    branches: [ master ]
    
jobs:
  push-image-to-docker-hub:
    runs-on: ubuntu-latest

    env:
      DOCKER_PULL_COMMAND: docker buildx build --platform linux/amd64 --output type=image,push=true -t ${{ secrets.DOCKER_STORAGE_IP }}/mckismetlab-api-server .

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest
        buildkitd-flags: --debug
      
    - name: Login to private registry
      uses: docker/login-action@v2
      with:
        registry: mckismetlab.net
        username: ${{ secrets.MCKISMETLAB_DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.MCKISMETLAB_DOCKER_REGISTRY_PASSWORD }}
      
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
      
    - name: Build the Docker image And Push
      id: firs-docker-pull
      run: ${{ env.DOCKER_PULL_COMMAND }}
      continue-on-error: true

    - name: Retry again on failure Build the Docker image And Push
      id: second-docker-pull
      if: steps.firs-docker-pull.outcome != 'success'
      run: ${{ env.DOCKER_PULL_COMMAND }}

    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v2
      env:
        webhook_url: ${{ secrets.WEBHOOK_URL }}/mkl-api-build-webhook
        webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
